<table class="fieldtitle" width="990" cellpadding="0" cellspacing="0" border="0">        
    <tr>
        <td id="tdLast5YearTeam" align="center">
            &nbsp;
        </td>
    </tr>
    <tr height="10">
        <td>
        </td>
    </tr>
    <tr>
        <td id="tdTeam_RSSummary" align="center">
            &nbsp;
        </td>
    </tr>
    <tr height="10">
        <td>
        </td>
    </tr>
    <tr>
        <td id="tdLast5YearLeague" align="center">
            &nbsp;
        </td>
    </tr>
    <tr height="10">
        <td>
        </td>
    </tr>
    <tr>
        <td id="tdLeague_RSSummary" align="center">
            &nbsp;
        </td>
    </tr>
    <tr height="10">
        <td>
        </td>
    </tr>
    <tr>
        <td id="tdNormalTable" align="center">
            &nbsp;
        </td>
    </tr>
    <tr height="20">
        <td>
        </td>
    </tr> 
</table>